import * as Reaflow from 'reaflow';
import React, { useRef, useState } from 'react';
import ReactDOM from 'react-dom';
import * as FramerMotion from 'framer-motion';
import * as RDK from 'rdk';
import ClassNames from 'classnames';
window.Reaflow = Reaflow;
window.React = React;
window.ReactDOM = ReactDOM;
window.RDK = RDK;
window.FramerMotion = FramerMotion;
window.ClassNames = ClassNames;